name: pandockering
on: workflow_dispatch
jobs:
  pandocker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/core
        with:
          args: "--version"  # gets appended to pandoc command
