name: pandockering
on: workflow_dispatch
jobs:
  pandocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/core
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=output/index.html
            README.md
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
